application:
  debug: true
  debugLevel: DEBUG
  save:
    metrics:
     required: false
     filename: mySavedMetrics.json
ibm:
  mq:
    multiInstance: false
    queueManager: PQ0114
    channel: GLEO3.PQ0114
    connName: smq-ssl-multi-gleo-prod-ibm-mq-qm-apmm-cp4i-demo1.roks-cp4iv2-2face0433451d5f4f63e8f7ab10f8f12-0000.eu-de.containers.appdomain.cloud(443)
    mqHostName: smq-ssl-multi-gleo-prod-ibm-mq-qm-apmm-cp4i-demo1.roks-cp4iv2-2face0433451d5f4f63e8f7ab10f8f12-0000.eu-de.containers.appdomain.cloud
    mqPort: 443
    sslCipherSpec: TLS_RSA_WITH_AES_256_CBC_SHA256
    useSSL: true
    user: johndoe
    password: 
    local: false
    keepMetricsWhenQueueManagerIsDown: false
    clearMetrics: 5
    json:
      sort: true
      order: ascending
    objects:
      queues:
        include: "*"
        #include: GLEO
        exclude: SYSTEM.,AMQ.,DUMMY,ERROR.HANDLER
      channels:
        include: "*"
        exclude: SYSTEM.,ADMIN.TLS.SVRCONN
      listeners:
        include: "*"
        exclude: SYSTEM.
        types:
          include: TCP
          exclude: "*" 
    event:
      delayInMilliSeconds: 10000
    security:
      truststore: clientkey.jks
      truststore-password: surajit
      keystore: clientkey.jks
      keystore-password: surajit
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, metrics
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
info:
  app:
    name: MQ-Metrics
    description: IBM MQ Metrics
    version: 1.0.0.11
    java:
      version: 1.8.0.0
server:
  port:
    8081